### ISSUE TITLE
Toggle graphs using checkboxes

### ISSUE THREAD

**Issue by abhishek0208** [yboulkaid/osemosys-cloud-visualization#17]
Goal: make it easier to find the relevant graph in the visualization.
- Add a checkbox for each figure to the top of the visualization window.
- All checkboxes are checked by default.
- Unchecking a box will hide the corresponding figure.
- Add a button to uncheck all boxes.

**Comment by yboulkaid** [comment]
This has been done in https://github.com/yboulkaid/osemosys-cloud-visualization/pull/25

Note: the button to uncheck all boxes has been skipped because there was no easy way to do it using the [`dcc.Checklist`](https://dash.plotly.com/dash-core-components/checklist) component. Instead the app remembers which boxes have been checked between sessions users do not need to uncheck the boxes every time
